Fix sgl-router startup crash
This fixes a possible crash during startup in some environments that looks like this:

```
2025-06-25 15:01:45  INFO sglang_router_rs::server: src/server.rs:312: 🚧 Initializing Prometheus metrics on 127.0.0.1:29000
2025-06-25 15:01:45  INFO sglang_router_rs::server: src/server.rs:321: 🚧 Initializing router on 0.0.0.0:30000
2025-06-25 15:01:45  INFO sglang_router_rs::server: src/server.rs:322: 🚧 Initializing workers on ["http://10.0.0.1:30000", "http://10.0.0.2:30000", "http://10.0.0.3:30000"]
2025-06-25 15:01:45  INFO sglang_router_rs::server: src/server.rs:323: 🚧 Policy Config: CacheAwareConfig { cache_threshold: 0.5, balance_abs_threshold: 32, balance_rel_threshold: 1.0001, eviction_interval_secs: 60, max_tree_size: 16777216, timeout_secs: 300, interval_secs: 10 }
2025-06-25 15:01:45  INFO sglang_router_rs::server: src/server.rs:324: 🚧 Max payload size: 256 MB
2025-06-25 15:01:45  INFO sglang_router_rs::server: src/server.rs:334: 🚧 Service discovery disabled

thread '<unnamed>' panicked at /home/router/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.1/src/runtime/blocking/shutdown.rs:51:21:
Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.
```