[BugFix] Fix CPU inference failure
Main branch tip failed on CPU with error logs below, as the device_name is None if run on CPU.

```
  File "/home/cyb/sglang/python/sglang/srt/server_args.py", line 1446, in _handle_model_specific_adjustments
    is_h20_device = "H20" in device_name and "H200" not in device_name
                    ^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```